<table>
<?php
include "inc/db.php";
$vege = array(
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/asparagus/',"name"=>'Asparagus'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/broccoli/',"name"=>'Broccoli'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-do-carrots-last-shelf-life/',"name"=>'Carrots'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/canned-vegetables-shelf-life-expiration-date/',"name"=>'Canned Vegetables'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/canned-vegetables-shelf-life-expiration-date/',"name"=>'Canned Vegetable Soup'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/cauliflower/',"name"=>'Cauliflower'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-celery-last-shelf-life/',"name"=>'Celery'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/corn/',"name"=>'Corn'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/canned-vegetables-shelf-life-expiration-date/',"name"=>'Corn - Canned'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Corn - Frozen'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-do-cucumbers-last-shelf-life-expiration-date/',"name"=>'Cucumbers'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Frozen Vegetables'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Frozen Carrots'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Frozen Corn'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Frozen Peas'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Frozen String Beans'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-garlic-last-shelf-life',"name"=>'Garlic'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/green-beans/',"name"=>'Green Beans'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/kale/',"name"=>'Kale'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-lettuce-last',"name"=>'Lettuce'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/mushrooms/',"name"=>'Mushrooms'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-do-onions-last-shelf-life/',"name"=>'Onions'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/bell-peppers/',"name"=>'Peppers'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-pickles-last/',"name"=>'Pickles'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-pickles-last/',"name"=>'Pickled Peppers'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-pickles-last/',"name"=>'Pickled Corn'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/potatoes-shelf-life-expiration-date/',"name"=>'Potatoes'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/parsnips/',"name"=>'Parsnips'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-pumpkin-last/',"name"=>'Pumpkin'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/salad-shelf-life-expiration-date/',"name"=>'Salad'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/salsa-shelf-life-expiration-date/',"name"=>'Salsa'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-pickles-last/',"name"=>'Sauerkraut (Pickled Cabbage)'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-nori-last-shelf-life/',"name"=>'Seaweed (Nori)'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/spaghetti-sauce-shelf-life-expiration-date/',"name"=>'Spaghetti Sauce'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/spinach/',"name"=>'Spinach'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-summer-squash-last/',"name"=>'Summer Squash'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-do-sweet-potatoes-or-yams-last/',"name"=>'Sweet Potatoes'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/tomatoes-shelf-life-expiration-date',"name"=>'Tomatoes'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/canned-vegetables-shelf-life-expiration-date/',"name"=>'Vegetables - Canned'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/frozen-vegetables-shelf-life-expiration-date/',"name"=>'Vegetables - Frozen'],
["categoty"=>'vegetables',"url"=>'http://www.eatbydate.com/how-long-does-winter-squash-last/',"name"=>'Winter Squash']
);
$dairy = array(
["categoty"=>'15',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Almond Milk'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/cheese-shelf-life-expiration-date/',"name"=>'Asiago Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-infant-formula-last-shelf-life-expiration-date/',"name"=>'Baby Formula'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/spreads/butter-shelf-life-expiration-date/',"name"=>'Butter'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/spreads/butter-shelf-life-expiration-date/',"name"=>'Butter - with Oil'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/brie-feta-mozzarella-soft-cheese-shelf-life-expiration-date/',"name"=>'Brie Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/cheese-shelf-life-expiration-date/',"name"=>'Cheddar Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Coconut Milk'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Coffee Cream'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-coffee-mate-last-shelf-life/',"name"=>'Coffee-Mate - Liquid '],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-coffee-mate-last-shelf-life/',"name"=>'Coffee-Mate - Powder '],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Cool Whip'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/cottage-cheese-shelf-life-expiration-date/',"name"=>'Cottage Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Cream - Half &amp; Half'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Cream - Heavy'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Cream - Light'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Cream - Whipping'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/cream-cheese-shelf-life-expiration-date/',"name"=>'Cream Cheese - Regular'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/cream-cheese-shelf-life-expiration-date/',"name"=>'Cream Cheese - Reduced Fat'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Egg Substitutes'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog - Canned'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog - Homemade'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Egg Whites'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Egg Yolks'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Eggs - Fresh'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/hard-boiled-eggs-shelf-life-expiration-date/',"name"=>'Eggs - Hard Boiled'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-evaporated-milk-last-shelf-life/',"name"=>'Evaporated Milk'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/brie-feta-mozzarella-soft-cheese-shelf-life-expiration-date/',"name"=>'Feta Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date/',"name"=>'Frozen Yogurt'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date/',"name"=>'Greek Yogurt'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Half and Half'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Hard Boiled Eggs (Shell On)'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Hard Boiled Eggs (Shell Off)'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/brie-feta-mozzarella-soft-cheese-shelf-life-expiration-date/',"name"=>'Havarti Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/ice-cream-shelf-life-expiration-date/',"name"=>'Ice Cream'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-margarine-last-shelf-life-expiration-date/',"name"=>'Margarine'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk  - Lactose-Free'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Non-Fat'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Skim'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Reduced-Fat'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Whole'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/brie-feta-mozzarella-soft-cheese-shelf-life-expiration-date/',"name"=>'Mozzarella Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/brie-feta-mozzarella-soft-cheese-shelf-life-expiration-date/',"name"=>'Muenster Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/cream-cheese-shelf-life-expiration-date/',"name"=>'Neufchatel Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/cheese-shelf-life-expiration-date/',"name"=>'Parmesan Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/milk/how-long-does-powdered-milk-last-shelf-life/',"name"=>'Powdered Milk'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/pudding-shelf-life-expiration-date/',"name"=>'Pudding'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Rice Milk'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/cottage-cheese-shelf-life-expiration-date/',"name"=>'Ricotta Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/cheese-shelf-life-expiration-date/',"name"=>'Romano Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/sour-cream-shelf-life-expiration-date/',"name"=>'Sour Cream - Regular'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/sour-cream-shelf-life-expiration-date/',"name"=>'Sour Cream - Reduced Fat'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/sour-cream-shelf-life-expiration-date/',"name"=>'Sour Cream Based Dips'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Soy Milk'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/how-long-does-condensed-milk-last-shelf-life/',"name"=>'Sweetened Condensed Milk '],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/cheese/cheese-shelf-life-expiration-date/',"name"=>'Swiss Cheese'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy-coffee-cream-shelf-life-expiration-date/',"name"=>'Whipping Cream'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date/',"name"=>'Yogurt (Yoghurt)'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date/',"name"=>'Yogurt - Drinkable'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date/',"name"=>'Yogurt - Reduced-Fat'],
["categoty"=>'15',"url"=>'http://www.eatbydate.com/dairy/yogurt-shelf-life-expiration-date/',"name"=>'Yogurt - With Fruit']
);
$fruits = array(
["categoty"=>'5',"url"=>'http://www.eatbydate.com/canned-fruit-shelf-life-expiration-date',"name"=>'Canned Fruit'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date',"name"=>'Dried Fruit'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/how-long-do-avocados-last-shelf-life-expiration-date/',"name"=>'Avocados'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Apricots - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/apricots/&quot;',"name"=>'Apricots - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date',"name"=>'Blueberries - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/blueberries',"name"=>'Blueberries - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/bananas-shelf-life-expiration-date/',"name"=>'Bananas - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Banana - Chips'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/how-long-do-coconuts-last-shelf-life/',"name"=>'Coconut - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/how-long-do-coconuts-last-shelf-life/',"name"=>'Coconut - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Craisins - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Cranberries - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Cherries - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/cherries/',"name"=>'Cherries - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-maraschino-cherries-last-shelf-life/',"name"=>'Cherries - Maraschino'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Chocolate Cherries'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Dates - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/frozen-fruit-shelf-life-expiration-date/',"name"=>'Frozen Fruit'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/figs',"name"=>'Figs - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/grapes',"name"=>'Grapes - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/how-long-do-lemons-last/',"name"=>'Lemons - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Mangoes - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-maraschino-cherries-last-shelf-life/',"name"=>'Maraschino Cherries'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/how-long-do-oranges-last-shelf-life-expiration-date/',"name"=>'Oranges - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/peaches/',"name"=>'Peaches - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/pineapples',"name"=>'Pineapple - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/how-long-does-pumpkin-last/',"name"=>'Pumpkin - Canned'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/how-long-does-pumpkin-last/',"name"=>'Pumpkin - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/other/condiments/olives/',"name"=>'Olives'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/fruits/fresh/how-long-do-strawberries-last/',"name"=>'Strawberries - Fresh'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/dried-fruit-shelf-life-expiration-date/',"name"=>'Strawberries - Dried'],
["categoty"=>'5',"url"=>'http://www.eatbydate.com/tomatoes-shelf-life-expiration-date/',"name"=>'Tomatoes - Fresh']
);
$drinks = array(
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Soft Drink'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Almond Milk'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Apple Cider - Fresh'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Apple Juice - Bottle'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Apple Juice - Can'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Apple Juice - Box'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-beer-last-shelf-life/',"name"=>'Beer - Cans'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-beer-last-shelf-life/',"name"=>'Beer - Bottles'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-beer-last-shelf-life/',"name"=>'Beer - Homemade'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-beer-last-shelf-life/',"name"=>'Beer - Light'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',"name"=>'Brandy'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Capri Sun Box'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-champagne-last-shelf-life/',"name"=>'Champagne'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Citrus juice - Fresh Squeezed'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Coconut Milk'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/coffee-shelf-life-expiration-date/',"name"=>'Coffee - Ground '],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/coffee-shelf-life-expiration-date/',"name"=>' Coffee - Whole Bean '],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Coca Cola Can'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Coke - Diet Can'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Cranberry Juice Cocktail'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog - Reduced Fat'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog - Canned'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-egg-nog-last-shelf-life-expiration-date/',"name"=>'Egg Nog - Homemade'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-infant-formula-last-shelf-life-expiration-date/',"name"=>'Enfamil'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/ensure/',"name"=>'Ensure'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-evaporated-milk-last-shelf-life/',"name"=>'Evaporated Milk'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Fruit Juice Concentrate'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',"name"=>'Gatorade - Bottles'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',"name"=>'Gatorade - Dry Powder'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-evaporated-milk-last-shelf-life/',"name"=>'Evaporated Milk - Regular'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-evaporated-milk-last-shelf-life/',"name"=>'Evaporated Milk - Skim'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',"name"=>'Gin'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Grape Juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Grapefruit Juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Guava juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Hawaiian Punch - Can'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Hemp Milk'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-infant-formula-last-shelf-life-expiration-date/',"name"=>'Infant Formula'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-do-kcups-last-shelf-life/',"name"=>'Kcup Coffee'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-do-kcups-last-shelf-life/',"name"=>'Kcup Tea'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-do-kcups-last-shelf-life/',"name"=>'Kcup Hot Chocolate'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-do-kcups-last-shelf-life/',"name"=>'Kcup Apple Cider'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Mango Juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Lactose Free'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Non-Fat'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Reduced Fat'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Skim'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/dairy/milk/milk-shelf-life-expiration-date/',"name"=>'Milk - Whole'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Minute Maid Box'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Ocean Spray Cranberry Juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Orange Juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Orange Soda - Bottle'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Pepsi - Bottle'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Pepsi - Can'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-coke-last-shelf-life-expiration-date/',"name"=>'Pepsi - Diet Can'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',"name"=>'Powerade'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',"name"=>'Propel'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',"name"=>'Rum'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',"name"=>'Sport Drinks'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/tea-shelf-life-expiration-date/',"name"=>'Tea - Bags'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/tea-shelf-life-expiration-date/',"name"=>'Tea Loose'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/tea-shelf-life-expiration-date/',"name"=>'Tea - Powder'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/tea-shelf-life-expiration-date/',"name"=>'Tea - Prepared '],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Rice Milk'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Soy Milk'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',"name"=>'Tequila'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Treetop Apple Juice'],  
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-water-last-shelf-life-expiration-date/',"name"=>'Water - Bottled '],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-water-last-shelf-life-expiration-date/',"name"=>'Water - Flavored (Liquid and Powder)'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-water-last-shelf-life-expiration-date/',"name"=>'Water - Vitamin '],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/sport-drinks-shelf-life-expiration-date/',"name"=>'Water - Sparkling '],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-champagne-last-shelf-life/',"name"=>'Sparkling Wine'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/how-long-does-champagne-last-shelf-life/',"name"=>'Vintage Champagne'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',"name"=>'Vodka'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/fruit-juice-shelf-life-expiration-date/',"name"=>'Welch\'s Grape Juice'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/drinks/alcohol/alcohol-shelf-life-expiration-date/',"name"=>'Whiskey'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/wine-shelf-life-expiration-date/',"name"=>'White Wine - Bottle'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/wine-shelf-life-expiration-date/',"name"=>'Red Wine - Bottle'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/wine-shelf-life-expiration-date/',"name"=>'Wine Juice Box'],
["categoty"=>'16',"url"=>'http://www.eatbydate.com/wine-shelf-life-expiration-date/',"name"=>'Fine Wine']
);
$grain = array(
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/bread-shelf-life-expiration-date/',"name"=>'Bread - Bakery'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/bread-shelf-life-expiration-date/',"name"=>'Bread - Packaged'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/bread-shelf-life-expiration-date/',"name"=>'Bread - Crumbs'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cake-shelf-life-expiration-date/',"name"=>'Cake - Bakery'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cake-shelf-life-expiration-date/',"name"=>'Cake - With Fresh Fruit'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cake-shelf-life-expiration-date/',"name"=>'Cake - With Whipped Cream'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cake-shelf-life-expiration-date/',"name"=>'Cake - Fruitcake'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/cereal-shelf-life-expiration-date/',"name"=>'Cereal - Box'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cheesecake-shelf-life/',"name"=>'Cheesecake'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Bakery'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Packaged Hard'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Packaged Soft'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Homemade Hard'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Homemade Soft'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/bread-shelf-life-expiration-date/',"name"=>'Croutons'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes - Bakery'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes - Fresh Fruit'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes - Whipped Cream'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes - Cream Cheese'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes - Homemade'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes - Hostess '],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/lasagna/',"name"=>'Lasagna'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',"name"=>'Oatmeal - Instant'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',"name"=>'Oatmeal - Flavored'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',"name"=>'Oatmeal - Minute'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',"name"=>'Oatmeal - 5 Minute'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',"name"=>'Oatmeal - Irish'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/cereal/how-long-does-oatmeal-last-shelf-life-expiration-date-storage/',"name"=>'Oatmeal - Cooked'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/sweets/oreos-shelf-life-expiration-date/',"name"=>'Oreos'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',"name"=>'Pasta - Dry'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',"name"=>'Noodles - Dry'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',"name"=>'Pasta - Fresh'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',"name"=>'Noodles - Fresh'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',"name"=>'Pasta - Cooked'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pasta-shelf-life-expiration-date/',"name"=>'Noodles - Cooked'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pizza-shelf-life-expiration-date/',"name"=>'Pizza - Dominos'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pizza-shelf-life-expiration-date/',"name"=>'Pizza - Frozen'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/pizza-shelf-life-expiration-date/',"name"=>'Pizza - Homemade'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pie - Fruit'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pie- Fresh Fruit'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pie - Cream'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pie - Custard'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pie - Pumpkin'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pie - Quiche'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/pie-shelf-life-expiration-date/',"name"=>'Pot Pie'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-pop-tarts-last-shelf-life-expiration-date',"name"=>'Pop Tarts'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - White'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Oxygen Free'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Brown'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Wild'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Minute'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Cooked-White'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Cooked-Brown'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/rice-shelf-life-expiration-date/',"name"=>'Rice - Cooked-Wild'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/stuffing-shelf-life-expiration-date/',"name"=>'Stuffing - package dry'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/stuffing-shelf-life-expiration-date/',"name"=>'Stove Top Stuffing Mix'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/stuffing-shelf-life-expiration-date/',"name"=>'Stuffing - Prepared'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/stuffing-shelf-life-expiration-date',"name"=>'Stuffing - Homemade'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-pop-tarts-last-shelf-life-expiration-date',"name"=>'Toaster Strudel'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-tortillas-last-shelf-life-expiration-date/',"name"=>'Tortillas - Flour'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-tortillas-last-shelf-life-expiration-date/',"name"=>'Tortillas - Corn'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-tortillas-last-shelf-life-expiration-date/',"name"=>'Tortillas - Spinach'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-tortillas-last-shelf-life-expiration-date/',"name"=>'Tortillas - Whole Wheat'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/baked-goods/how-long-do-tortillas-last-shelf-life-expiration-date/',"name"=>'Tortillas - Homemade'],
["categoty"=>'18',"url"=>'http://www.eatbydate.com/grains/quinoa/',"name"=>'Quinoa']
);
$proteins = array(
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',"name"=>'Almonds'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/soy-rice-almond-milk-substitutes-shelf-life-expiration-date/',"name"=>'Almond Milk'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/bacon-shelf-life-expiration-date/',"name"=>'Bacon - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/bacon-shelf-life-expiration-date/',"name"=>'Bacon - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/bacon-shelf-life-expiration-date/',"name"=>'Bacon Bits'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/beans-shelf-life-expiration-date/',"name"=>'Bean Sprouts'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/beans-shelf-life-expiration-date/',"name"=>'Beans - Canned'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/beans-shelf-life-expiration-date/',"name"=>'Beans - Dried'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Beef - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Beef - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Beef Jerky'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/deli-meat-shelf-life-expiration-date/',"name"=>'Bologna'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-canned-meat-last-shelf-life-expiration-date/',"name"=>'Canned Meat'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',"name"=>'Cashews'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/chia-seeds/',"name"=>'Chia'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-chicken-broth-last-shelf-life/',"name"=>'Chicken Broth'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-chicken-last-shelf-life-expiration-date/',"name"=>'Chicken - Canned'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-chicken-last-shelf-life-expiration-date/',"name"=>'Chicken - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-chicken-last-shelf-life-expiration-date/',"name"=>'Chicken - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-chicken-last-shelf-life-expiration-date/',"name"=>'Chicken - Roasted'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Corned Beef - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Corned Beef - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/deli-meat-shelf-life-expiration-date/',"name"=>'Deli Meat'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/eggs-shelf-life-expiration-date/',"name"=>'Eggs - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/hard-boiled-eggs-shelf-life-expiration-date/',"name"=>'Eggs - Hard Boiled'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/fish-shelf-life-expiration-date/',"name"=>'Fish'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/nuts/flax-seeds/',"name"=>'Flax'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/beans-shelf-life-expiration-date/',"name"=>'Green Beans - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Ground Beef - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Ground Beef - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-pork-last/',"name"=>'Ground Pork'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/ham-shelf-life-expiration-date/',"name"=>'Ham - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/ham-shelf-life-expiration-date/',"name"=>'Ham - Unopened'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/hamburgers-shelf-life-expiration-date/',"name"=>'Hamburger - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/hamburgers-shelf-life-expiration-date/',"name"=>'Hamburger - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/hot-dogs-shelf-life-expiration-date/',"name"=>'Hot Dogs - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/hot-dogs-shelf-life-expiration-date/',"name"=>'Hot Dogs - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/beans-shelf-life-expiration-date/',"name"=>'Hummus'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/deli-meat-shelf-life-expiration-date/',"name"=>'Luncheon Meat'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-peanut-butter-last-shelf-life-expiration-date-food-storage/',"name"=>'Peanut Butter - Crunchy'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-peanut-butter-last-shelf-life-expiration-date-food-storage/',"name"=>'Peanut Butter - Natural'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-peanut-butter-last-shelf-life-expiration-date-food-storage/',"name"=>'Peanut Butter - Smooth'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',"name"=>'Peanuts'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',"name"=>'Pecans'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',"name"=>'Pistachios'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-shrimp-last/',"name"=>'Pokey'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-pork-last/',"name"=>'Pork Chops'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-pork-last/',"name"=>'Pork Loin'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-salmon-last-shelf-life/',"name"=>'Salmon - Canned'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-salmon-last-shelf-life/',"name"=>'Salmon - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-salmon-last-shelf-life/',"name"=>'Salmon - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/fish-shelf-life-expiration-date/',"name"=>'Sardines - Canned'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-shrimp-last/',"name"=>'Sashimi'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-pork-last/',"name"=>'Sausage'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-shrimp-last/',"name"=>'Shrimp - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-shrimp-last/',"name"=>'Shrimp - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-shrimp-last/',"name"=>'Sushi'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/fish-shelf-life-expiration-date/',"name"=>'Tuna - Canned'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/fish-shelf-life-expiration-date/',"name"=>'Tuna - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/deli-meat-shelf-life-expiration-date/',"name"=>'Salami'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/nuts/sesame-seeds/',"name"=>'Sesame Seeds'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-canned-meat-last-shelf-life-expiration-date/',"name"=>'Spam'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Steak - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Steak - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/nuts/sesame-seeds/',"name"=>'Sunflower Seeds'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-tofu-last-shelf-life/',"name"=>'Tofu - Opened'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-does-tofu-last-shelf-life/',"name"=>'Tofu - Unopened'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/proteins/meats/beef-shelf-life-expiration-date/',"name"=>'Turkey Jerky'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/turkey-shelf-life-expiration-date/',"name"=>'Turkey - Cooked'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/turkey-shelf-life-expiration-date/',"name"=>'Turkey - Fresh'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/turkey-shelf-life-expiration-date/',"name"=>'Turkey - Ground'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/turkey-shelf-life-expiration-date/',"name"=>'Turkey Salad'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/turkey-shelf-life-expiration-date/',"name"=>'Turkey Soup'],
["categoty"=>'19',"url"=>'http://www.eatbydate.com/how-long-do-nuts-last-shelf-life-expiration-date/',"name"=>'Walnuts']
);

$others = array(
["categoty"=>'20',"url"=>'http://www.eatbydate.com/baking-powder-shelf-life-expiration-date/',"name"=>'Baking Powder'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/baking-soda-shelf-life-expiration-date/',"name"=>'Baking Soda'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/spices/how-long-does-basil-last/',"name"=>'Basil'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/condiments/how-long-does-bbq-sauce-last-shelf-life-expiration-date/',"name"=>'BBQ Sauce'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cake-mix-shelf-life-expiration-date/',"name"=>'Brownie Mix'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-sugar-last/',"name"=>'Brown Sugar'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cake-shelf-life-expiration-date/',"name"=>'Cake'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cake-shelf-life-expiration-date/',"name"=>'Cake - Cream'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cake-mix-shelf-life-expiration-date/',"name"=>'Cake Mix'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-candy-canes-last/',"name"=>'Candy Canes'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/chocolate-shelf-life-expiration-date/',"name"=>'Chocolate'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/chocolate-shelf-life-expiration-date/',"name"=>'Chocolate Chips'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/chocolate-shelf-life-expiration-date/',"name"=>'Chocolate Truffles'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/chocolate-shelf-life-expiration-date/',"name"=>'Chocolate - Belgian'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/spices/how-long-does-cinnamon-last-shelf-life-expiration-date/',"name"=>'Cinnamon'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/sweets/how-long-does-cocoa-last-shelf-life/',"name"=>'Cocoa'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/baking/cookie-dough/',"name"=>'Cookies Dough'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Homemade'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Hard'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Soft'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cookies-shelf-life-expiration-date/',"name"=>'Cookies - Packaged'],                   
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/baking/cornmeal/',"name"=>'Cornmeal'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-cornstarch-last-shelf-life/',"name"=>'Cornstarch'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-cranberry-sauce-last/',"name"=>'Cranberry Sauce'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>'Cream Pie'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-crisco-last-shelf-life-expiration-date-storage-tips/',"name"=>'Crisco'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-cupcakes-last-shelf-life/',"name"=>'Cupcakes'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/dry-ice/',"name"=>'Dry Ice'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-fish-sauce-last-shelf-life/',"name"=>'Fish Sauce'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-flour-last-shelf-life-expiration-date/',"name"=>'Flour'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-frosting-last/',"name"=>'Frosting Can'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-frosting-last/',"name"=>'Frosting - Homemade'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cake-shelf-life-expiration-date/',"name"=>'Fruit Cake'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>'Fruit Pie'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/spices/how-long-does-ginger-last-shelf-life/',"name"=>'Ginger'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/sweets/gingerbread/',"name"=>'Gingerbread'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/snacks/guacamole-shelf-life-expiration-date/',"name"=>'Guacamole'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-jelly-beans-last-shelf-life-expiration-date/',"name"=>'Gummy Candy'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/snacks/hummus/',"name"=>'Hummus'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/ice-cream-shelf-life-expiration-date/',"name"=>'Ice Cream'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-frosting-last/',"name"=>'Icing'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-jam-last-shelf-life-expiration-date/',"name"=>'Jam'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-jello-last-shelf-life/',"name"=>'Jello'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-jelly-beans-last-shelf-life-expiration-date/',"name"=>'Jelly Beans'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-sprinkles-last-shelf-life-expiration-date/',"name"=>'Jimmies'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/ketchup-shelf-life-expiration-date/',"name"=>'Ketchup'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/sweets/mms/',"name"=>'M&amp;M\'s'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/condiments/how-long-do-maraschino-cherries-last-shelf-life/',"name"=>'Maraschino Cherries'], 
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-marshmallows-last/',"name"=>'Marshmallows'], 
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-molasses-last-shelf-life/',"name"=>'Molasses'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/cake-mix-shelf-life-expiration-date/"<li="',"name"=>'Muffin Mix'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-mustard-last/',"name"=>'Mustard'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/condiments/how-long-does-nutella-last-shelf-life/',"name"=>'Nutella'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com//other/condiments/olives/',"name"=>'Olives'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/oreos-shelf-life-expiration-date/',"name"=>'Oreos'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pesto/',"name"=>'Pesto'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>'Pie - Fruit Filling'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>'Pie - Fresh Fruit'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>' Pie - Cream'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>' Pie - Custard'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>' Pie - Pumpkin'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-popcorn-last-shelf-life/',"name"=>'Popcorn'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-popsicles-last/',"name"=>'Popsicles'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/potato-chips-shelf-life-expiration-date/',"name"=>'Potato Chips'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-sugar-last/',"name"=>'Powdered Sugar'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/dairy/pudding-shelf-life-expiration-date/',"name"=>'Pudding - Packaged'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/dairy/pudding-shelf-life-expiration-date/',"name"=>'Pudding - Homemade'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/pie-shelf-life-expiration-date/',"name"=>'Pumpkin Pie'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/vegetables/fresh-vegetables/salsa-shelf-life-expiration-date/',"name"=>'Salsa'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/spices/how-long-does-salt-last-shelf-life/',"name"=>'Salt'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/ice-cream-shelf-life-expiration-date/',"name"=>'Sherbert'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-crisco-last-shelf-life-expiration-date-storage-tips/',"name"=>'Shortening'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-jelly-beans-last-shelf-life-expiration-date/',"name"=>'Skittles'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/other/how-long-do-spices-last/',"name"=>'Spices'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-do-sprinkles-last-shelf-life-expiration-date/',"name"=>'Sprinkles'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-sugar-last/',"name"=>'Sugar'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-sugar-last/',"name"=>'Sweet n Low'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-syrup-last/',"name"=>'Syrup'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-vanilla-extract-last-shelf-life/',"name"=>'Vanilla'],
["categoty"=>'20',"url"=>'http://www.eatbydate.com/how-long-does-vinegar-last/&quot;',"name"=>'Vinegar'],
["categoty"=>'20',"url"=>'hhttp://www.eatbydate.com/other/condiments/how-long-does-wasabi-last-shelf-life/',"name"=>'Wasabi'],
["categoty"=>'20',"url"=>'hhttp://www.eatbydate.com/other/baking/yeast/',"name"=>'Yeast']
);
function getHtml($url){
	ob_start(); 
	readfile($url);
	$output = ob_get_contents(); 
	ob_end_clean(); 	
	$start = stripos($output,'<table id="unopened">');
	$len = stripos($output,'</tbody></table>')-$start;
	return substr($output,$start+29,$len-29);
}
/* for ($i=0;$i<count($vege);$i++){
	$name = $vege[$i]["name"];
	$url = $vege[$i]["url"];
	$html = getHtml($url);
	$sql0 = "SELECT id,htmlid FROM datehtml WHERE url = '$url'";
	$res0 = $mysql->query($sql0);
	if(mysqli_num_rows($res0)>0){
		$id = $mysql->fetch($res0)[1];
	}else{
		$sql = "INSERT htmlcont VALUES ('','$html')";
		//$mysql->query($sql);
		$id = mysqli_insert_id($mysql->conn);
	}
	$sql1 = "INSERT datehtml VALUES ('',6,'$name','$url',$id)";
	//$mysql->query($sql1);
} */
/* for ($i=0;$i<count($dairy);$i++){
	$name = $dairy[$i]["name"];
	$url = $dairy[$i]["url"];
	$html = mysql_real_escape_string(getHtml($url)); //mysql_real_escape_string
	$sql0 = "SELECT id,htmlid FROM datehtml WHERE url = '$url'";
	$res0 = $mysql->query($sql0);
	if(mysqli_num_rows($res0)>0){
		$id = $mysql->fetch($res0)[1];
	}else{
		$sql = "INSERT htmlcont VALUES ('','$html')";
		$mysql->query($sql);
		$id = mysqli_insert_id($mysql->conn);
	}
	$sql1 = "INSERT datehtml VALUES ('',15,'$name','$url',$id)";
	$mysql->query($sql1);
} */

//echo $mysql->oneQuery("SELECT html from htmlcont where id =51");
function crawlhtml($ary,$cateid){
	global $mysql;
	for ($i=0;$i<count($ary);$i++){
		$name = $ary[$i]["name"];
		$url = $ary[$i]["url"];
		$html = mysql_real_escape_string(getHtml($url)); //mysql_real_escape_string
		$sql0 = "SELECT id,htmlid FROM datehtml WHERE url = '$url'";
		$res0 = $mysql->query($sql0);
		if(mysqli_num_rows($res0)>0){
			$id = $mysql->fetch($res0)[1];
		}else{
			$sql = "INSERT htmlcont VALUES ('','$html')";
			$mysql->query($sql);
			$id = mysqli_insert_id($mysql->conn);
		}
		$sql1 = "INSERT datehtml VALUES ('',$cateid,'$name','$url',$id)";
		$mysql->query($sql1);
	}
}
//crawlhtml($others,20);
?>
</table>